software_engineering/1_Project/index.rst
GPL forces publication independently of modifying the original work.
=> GPL was described as LGPL

python/README.rst, python/python/definitions.rst, python/python/introduction.rst, python/python/python2.rst
Small comments, move long type to Python2 specific segment, introduce binary and hexadecimal notation for ints.
=> Minor changes on my part

silx/introduction/index.rst
This is my review. Please update all items that are specific to the sections that your are preparing.
=> First pass of update of introduction

software_engineering/4_Virtualenv/index.rst
Update part related to virtual envs :
- Remove python2.7 and python3.4 related stuff (but keep the symlink hack)
- Add some details and clarifications
=> Remove python2.7-3.4 related stuff, add details

oop/OOP.ipynb
=> [fix] typos

python/python/0_Introduction.ipynb, python/python/1_Definitions.ipynb, python/python/2_Functions_Classes_Modules.ipynb
- Fix some typos
- Use `myadd(12, 6)` instead of `myadd(myparam1=12, myparam2=6)` in Part 1 (named arguments are not introduced yet at this stage)
- Add notes on how to comment code
=> Dec 2019 training: python intro

python/python/0_Introduction.ipynb, python/python/1_Definitions.ipynb, python/python/2_Functions_Classes_Modules.ipynb, python/python/3_input_output.ipynb
Fix some typos and remove unnecessarily confusing code from the parts 0, 1, 2.
=> Some corrections after the training

python/io/io_hdf5.ipynb, python/numpy/introduction_to_numpy.ipynb, python/python/0_Introduction.ipynb, python/python/1_Definitions.ipynb, python/python/2_Functions_Classes_Modules.ipynb
Some typos on the Python Intro training.
=> [WIP] Training 02 2020

python/python/0_Introduction.ipynb, python/python/3_input_output.ipynb
Some refresh for November 2020 training.
=> [November 2020] Part 1: updates and typos

python/python/2_Functions_Classes_Modules.ipynb
=> Changes to functions

optimization/Optimization.ipynb
A few questions:
- In **Introduction to GIL**:
> For example the shared variables n and m are no more allowed.
Why ?
> Moreover, the speed-up obtained (2) is far from the resources consumed (4)
I did not understand this sentence.
- In **Cython**:
> Use the cython -a to annotate the code to highlight potential hot-spots, in yellow.
Hot-spots in what sense ?
=> Modifications after test run

optimization/Addendum.ipynb
This is some material collected during the training ... to be integrated (or not) for next time we do the training.
=> Some alternative routes to be discussed

python/numpy/introduction_to_numpy.ipynb
=> [python] Fix numpy solution numbers and dtype deprecation warnings

python/io/io_hdf5.ipynb, python/io/solutions/exercise1.py, python/io/solutions/exercise2.py, python/io/solutions/exercise3.py
Some updates on the HDF5 part:  
- Remove warning "major version of h5py has been release end of 2020"
- Replace `OrderedDict` with native `dict` (same since python 3.6) - let's try to give something relatively simple to trainees
=> Training 2022-11-21: HDF5

software_engineering/4_Test/5_Test.ipynb
`clean_tests()` was deprecated in favor of `clean()`.
=> Update deprecated code

python/io/io_hdf5.ipynb
Typos + update of the list of compression filters provided by hdf5plugin
=> Update python/io parts

README.rst, binder/environment.yml
=> Binder update

gui/gui_edp_pyqt.ipynb, gui/imageplot.py, gui/laue.py
This PR:
- Reworks/updates the first part of the training
- Adds some words on how to read the C++ Qt doc for use in Python (closes #49)
- Adds Python typing to the provided code for the exercise
=> Rework GUI programming notebook

python/io/io_hdf5.ipynb
improvement of the h5py tutorial
* small reordering of the presentation (File reading -> File writing -> group browsing -> group writing -> dataset reading -> dataset writting)
* prefer usage of h5py.File context manager than any other
* add a section on attributes
* add a note on chunking
=> rework HDF5 part

python/io/io_hdf5.ipynb
A few updates following the last session. These are mostly to ensure that the slides can be properly displayed when the zoom level is high.
=> Update HDF5 part

python/numpy/introduction_to_numpy.ipynb
Add a clear example of using a boolean mask before creating a threshold mask on an array.
Solves issue #133
=> Introduce an example of a boolean mask
